# General Settings
SR_type: 'SISR' # [SISR, MISR] # dont forget to also set the sen2_amount
bands: 3

# Data Settings
Data:
  # Loader Settings
  train_batch_size: 24 #12
  val_batch_size: 8
  num_workers: 8

  # Detailed Dataset Setttings
  dataset_type: 'S2NAIP' # ['cv', 'SPOT6']
  data_dir: '/data1/simon/datasets/val_s2_tiles' # ['data/openImages/',''E:/thesis_paper/data/']
  spectral_matching: "none" #'histogram'
  sen2naip_settings:
    base_path: "/data2/simon/"
    dataset_type: "synthetic2"

# Model, Loss, Training  Settings
Model:
  load_checkpoint: False
  ckpt_path: "logs/GAN_NIR/2024-08-22_16-21-01/epoch=7-step=5008.ckpt"
Warmup:
  fusion: # train fusion in isolation previously
    enable: False
    epochs: 1
    lr: 0.0002

Generator:
  large_kernel_size: 9
  small_kernel_size: 3
  n_channels: 64
  n_blocks: 24 # 16
  scaling_factor: 0
  bands_in: 3
  bands_out: 1

Discriminator:
  kernel_size: 3
  n_channels: 64
  n_blocks: 8
  fc_size: 1024
  bands_in: 1

TruncatedVGG:
  i: 5
  j: 4

Optimizers:
  optim_g_lr: 1e-3
  optim_d_lr: 1e-3

Schedulers:
  metric: 'val/L1'
  patience_g: 25
  patience_d: 25
  factor_g: 0.25
  factor_d: 0.25
  verbose: True
  interval: 'epoch'

Losses:
  adv_loss_beta:  0.1

Logging:
  num_val_images: 1