base_configs:
  direction: "AtoB"
  isTrain: true
  #checkpoints_dir: "logs/checkpoints_px" # unused
  full_key: null
  name: "px"
  preprocess: null
  input_nc: 3 # RGB inputs. satclip embeds get added later, put here only input shape
  output_nc: 1
  ngf: 64
  ndf: 64
  netD: "basic"
  netG: "resnet_9blocks" # dont use a different version for now
  norm: "instance"
  no_dropout: true
  init_type: "normal"
  init_gain: 0.02
  n_layers_D: 3
  gan_mode: "lsgan"
  lr: 0.0002
  beta1: 0.5 # Adam optimizer beta1

  # Loss weights
  lambda_GAN: 1.0 # orig:1
  lambda_L1: 100.0 # orig: 100
  lambda_ssim: 0.0 # untested
  lambda_hist: 0.0

  # RS indices weights - 0 for skipping
  lambda_rs_losses: 0.0 # RS indices vs all others
  rs_losses_criterium: "l1" # RS indices loss criterion, [l1,l2]
  internal_rs_loss_weights:  # RS metrics internal weights
    lambda_ndvi: 0.33
    lambda_ndwi: 0.33
    lambda_evi: 0.33
    lambda_savi: 0.0
    lambda_msavi: 0.0
    lambda_gndvi: 0.0

# SatCLIP Settings
satclip:
  use_satclip: True # wether to use SatCLIP or not
  satclip_style: "inject" # ['inject', 'concat']
  satclip_inject_style: "multiply" # ['add', 'multiply']
  satclip_path: "model/satclip/satclip-resnet50-l10.ckpt"
  
  # post correction settings
  post_correction: False # learned post-correction parameter
  post_correction_init: 1.0 # initial value of post-correction parameter
  
  # Learned SatCLIP scaling parameter
  scaling_param: True # use learned scaling parameter?
  scaling_param_init: 0.01 # initial value of scale param

  # older settings, potentially remove
  # only used in addition style, 1.0 is no change
  #scaling_factor: 1.0 # 0.01 # scale embeddings to correlate with data range of input images
  

# Logging and PL-Trainer Settings
custom_configs:
  Logging:
    wandb_project: "exp_NIR_GAN_SatCLIP"
    num_val_images: 5
    log_ndvi: True
    log_input_stats: True
    check_val_every_n_epoch: 1
    time_series_frequency_epochs: 15
    time_series_log_all: False
  Model:
    load_checkpoint: False # Continue PL-Style
    ckpt_path: ""
    load_weights_only: True # Load ckpt file only
    weights_path: "logs/exp_NIR_GAN_SatCLIP/2025-03-07_14-52-31_SatCLIP_best/epoch=196-step=621600.ckpt"
  Training:
    accelerator: "cuda"
    devices: [2,3]
    strategy: "ddp" # ['ddp', 'dp']
  
  # setting sfor experimentation
  experimentation:
    save_val_df: True # saves validation dataframe at every epoch


# Optim Scheduler Settings
Schedulers:
  metric: 'val/L1'
  patience_g: 5
  patience_d: 5
  factor_g: 0.5
  factor_d: 0.5
  verbose: True
  interval: 'epoch'

# Data Settings
Data:
  normalize: False # TODO: removed this option
  
  # Dataloader Settings
  train_batch_size: 8 # 24 in normal scenario
  val_batch_size: 5
  num_workers: 16
  prefetch_factor: 2
  persistent_workers: True

  # Padding for removal of edge artifacts
  padding: False
  padding_amount: 10

  # Detailed Dataset Setttings
  # If mixed dataset, input list in dataset_type
  # If single dataset, input String in dataset_type
  # Options: ['SEN2NAIP', 'S2_rand', 'S2_75k',S2_100k,'worldstrat']
  dataset_type: ['SEN2NAIP','worldstrat'] # 'S2NAIP' # 'S2_rand' # 'S2_75k' # 'S2_100k' # 'worldstrat'
  
  
  # dataset settings
  sen2naip_settings:
    image_size: 256
    base_path: "/data2/simon/"
    dataset_type: "synthetic2"
    return_coords: True
  S2_rand_settings:
    image_size: 256
    base_path: "/data3/val_s2_tiles/"
    return_coords: True
    no_images: 1000
  S2_75k_settings:
    image_size: 256
    base_path: "/data2/simon/nirgan_s2/"
    continent_geojson: "/data2/simon/s100k/continents.geojson"
    return_clc_mask: True
    return_coords: True
  S2_100k_settings:
    image_size: 256
    base_path: "/data2/simon/s100k/images/"
    continent_geojson: "/data2/simon/s100k/continents.geojson"
    return_clc_mask: True
    return_coords: True
  worldstrat_settings:
    image_type: "hr" # ["lr","hr"]
    image_size: 256
    return_coords: True
  L8_15k_settings:
    base_path: "/data2/simon/nirgan_l8/"
    image_size: 256
    return_coords: True


  # TODO: check if we can remove this
  #data_dir:  #'/data1/simon/datasets/inf_data/' 
  #spectral_matching: "none" #'histogram'