base_configs:
  direction: "AtoB"
  isTrain: true
  checkpoints_dir: "logs/checkpoints_px"
  full_key: null
  name: "px"
  preprocess: null
  input_nc: 3
  output_nc: 1
  ngf: 64
  ndf: 64
  netD: "basic"
  netG: "resnet_9blocks"
  norm: "instance"
  no_dropout: true
  init_type: "normal"
  init_gain: 0.02
  n_layers_D: 3
  gan_mode: "lsgan"
  lr: 0.0002
  beta1: 0.5 # Adam optimizer beta1

  # Loss weights
  lambda_GAN: 1.0
  lambda_L1: 100.0
  lambda_ssim: 0.0
  use_training_pred_optimization: True

custom_configs:
  Logging:
    num_val_images: 1
  Model:
    load_checkpoint: False # Continue PL-Style
    ckpt_path: "logs/NIR_GAN/2025-02-04_12-02-41/last.ckpt"
    load_weights_only: True # Load ckpt file only
    weights_path: "logs/NIR_GAN/2025-02-04_12-02-41/last.ckpt"
Schedulers:
  metric: 'val/L1'
  patience_g: 50
  patience_d: 50
  factor_g: 0.5
  factor_d: 0.5
  verbose: True
  interval: 'epoch'

Data:
  normalize: False
  train_batch_size: 24
  val_batch_size: 5
  num_workers: 16
  prefetch_factor: 2
  persistent_workers: True

  padding: True
  padding_amount: 10

  # Detailed Dataset Setttings
  dataset_type: 'S2NAIP' # ['cv', 'SPOT6']
  data_dir: '/data1/simon/datasets/val_s2_tiles' # ['data/openImages/',''E:/thesis_paper/data/']
  spectral_matching: "none" #'histogram'
  sen2naip_settings:
    base_path: "/data2/simon/"
    dataset_type: "synthetic2"