base_configs:
  direction: "AtoB"
  isTrain: true
  #checkpoints_dir: "logs/checkpoints_px" # unused
  full_key: null
  name: "px"
  preprocess: null
  input_nc: 3 # RGB inputs. satclip embeds get added later, put here only input shape
  output_nc: 1
  ngf: 64
  ndf: 64
  netD: "basic"
  netG: "resnet_9blocks" # dont use a different version for now
  norm: "instance"
  no_dropout: true
  init_type: "normal"
  init_gain: 0.02
  n_layers_D: 3
  gan_mode: "lsgan"
  lr: 0.0002
  beta1: 0.5 # Adam optimizer beta1

  # Loss weights
  lambda_GAN: 1.0 # orig:1
  lambda_L1: 100.0 # orig: 100
  lambda_ssim: 0.0 # untested
  lambda_hist: 0.0

  # RS indices weights - 0 for skipping
  lambda_rs_losses: 0.0 # RS indices vs all others
  rs_losses_criterium: "l1" # RS indices loss criterion, [l1,l2]
  internal_rs_loss_weights:  # RS metrics internal weights
    lambda_ndvi: 0.2
    lambda_ndwi: 0.2
    lambda_evi: 0.2
    lambda_savi: 0.2
    lambda_msavi: 0.2
    lambda_gndvi: 0.0

# SatCLIP Settings
satclip:
  use_satclip: True # wether to use SatCLIP or not
  satclip_style: "inject" # ['inject', 'concat']
  satclip_inject_style: "multiply" # ['add', 'multiply']
  satclip_path: "model/satclip/satclip-resnet50-l10.ckpt"
  scaling_factor: 0.1 # scale embeddings to correlate with data range of input images - for add style

# Logging and PL-Trainer Settings
custom_configs:
  Logging:
    wandb_project: "exp_NIR_GAN_SatCLIP"
    num_val_images: 5
    log_ndvi: False
    log_input_stats: True
  Model:
    load_checkpoint: False # Continue PL-Style
    ckpt_path: ""
    load_weights_only: True # Load ckpt file only
    weights_path: "logs/exp_NIR_GAN/2025-03-04_18-24-49_S2NAIP/last.ckpt"

# Optim Scheduler Settings
Schedulers:
  metric: 'val/L1'
  patience_g: 100
  patience_d: 100
  factor_g: 0.5
  factor_d: 0.5
  verbose: True
  interval: 'epoch'

# Data Settings
Data:
  normalize: False # TODO: removed this option
  
  # Dataloader Settings
  train_batch_size: 24
  val_batch_size: 5
  num_workers: 16
  prefetch_factor: 2
  persistent_workers: True

  # Padding for removal of edge artifacts
  padding: True
  padding_amount: 10

  # Detailed Dataset Setttings
  dataset_type: 'S2NAIP' # ['S2NAIP', 'S2_rand', 'S2_75k','mixed']
  data_dir:  #'/data1/simon/datasets/inf_data/' 
  spectral_matching: "none" #'histogram'
  sen2naip_settings:
    image_size: 256
    base_path: "/data2/simon/"
    dataset_type: "synthetic2"
    return_coords: True
  S2_rand_settings:
    image_size: 256
    base_path: "/data3/val_s2_tiles/"
    return_coords: True
    no_images: 1000
  S2_75k:
    image_size: 256
    base_path: "/data2/simon/nirgan_s2/"
    return_coords: True
  S2_100k:
    image_size: 256
    base_path: "/data2/simon/s100k/images/"
    return_coords: True
  worldstrat_settings:
    image_size: 256
    return_coords: True
