# General Settings
SR_type: 'SISR' # [SISR, MISR] # dont forget to also set the sen2_amount
bands: 3

# Data Settings
Data:
  # Loader Settings
  train_batch_size: 8 #12
  val_batch_size: 5
  num_workers: 6
  prefetch_factor: 2 #8 #2

  # Detailed Dataset Setttings
  dataset_type: 'SEN2' # ['cv', 'SPOT6']
  data_dir: '/data1/simon/datasets/val_s2_tiles' # ['data/openImages/',''E:/thesis_paper/data/']
  sen2_amount: 4
  spectral_matching: 'histogram'
  return_type: 'cross_sensor' #interpolated_matched


# Model, Loss, Training  Settings
Model:
  load_checkpoint: True
  ckpt_path: "logs/GAN_NIR/2024-08-22_16-21-01/last.ckpt"
  load_fusion_checkpoint: False
  fusion_ckpt_path: 'logs\curated_ckpts\pretrained_Fusion.ckpt'
Warmup:
  fusion: # train fusion in isolation previously
    enable: False
    epochs: 1
    lr: 1e-4

Generator:
  large_kernel_size: 9
  small_kernel_size: 3
  n_channels: 64
  n_blocks: 24 # 16
  scaling_factor: 0
  bands_in: 3
  bands_out: 1

Discriminator:
  kernel_size: 3
  n_channels: 64
  n_blocks: 8
  fc_size: 1024
  bands_in: 1

TruncatedVGG:
  i: 5
  j: 4

Optimizers:
  optim_g_lr: 1e-4
  optim_d_lr: 1e-4

Schedulers:
  metric: 'val/L1'
  patience_g: 3
  patience_d: 3
  factor_g: 0.25
  factor_d: 0.25
  verbose: True
  interval: 'epoch'

Losses:
  adv_loss_beta:  1e-3

Logging:
  num_val_images: 5