base_configs:
  direction: "AtoB"
  isTrain: true
  checkpoints_dir: "logs/checkpoints_px"
  full_key: null
  name: "px"
  preprocess: null
  input_nc: 3
  output_nc: 1
  ngf: 64
  ndf: 64
  netD: "basic"
  netG: "resnet_9blocks"
  norm: "instance"
  no_dropout: true
  init_type: "normal"
  init_gain: 0.02
  n_layers_D: 3
  gan_mode: "lsgan"
  lr: 0.0002
  beta1: 0.5
  lambda_L1: 100.0

custom_configs:
  Logging:
    num_val_images: 1
  Model:
    load_checkpoint: False
    ckpt_path: ""

Schedulers:
  metric: 'discriminator_loss'
  patience_g: 15
  patience_d: 15
  factor_g: 0.25
  factor_d: 0.25
  verbose: True
  interval: 'epoch'

Data:
  train_batch_size: 32
  val_batch_size: 5
  num_workers: 8
  normalize: False
  prefetch_factor: 2

  # Detailed Dataset Setttings
  dataset_type: 'S2NAIP' # ['cv', 'SPOT6']
  data_dir: '/data1/simon/datasets/val_s2_tiles' # ['data/openImages/',''E:/thesis_paper/data/']
  spectral_matching: "none" #'histogram'
  sen2naip_settings:
    base_path: "/data2/simon/"
    dataset_type: "synthetic2"